"""Interactive cookie refresher for X.com and LinkedIn.

Opens a visible browser so you can log in, then automatically exports the
refreshed cookies to Netscape-format files that the pipeline reads.

Run this script whenever the pipeline reports authentication errors:

    python cookie_refresher.py             # refresh both
    python cookie_refresher.py --platform x
    python cookie_refresher.py --platform linkedin

The script detects whether you're already logged in before asking you to
log in again. After you confirm login, it saves the cookies and exits.
"""

import argparse
import asyncio
import logging
import os
import time
from pathlib import Path

from playwright.async_api import BrowserContext, async_playwright

logger = logging.getLogger(__name__)

USER_DATA_DIR = Path(os.getenv("USER_DATA_DIR", "./volumes/user_data"))

X_LOGIN_URL = "https://x.com/login"
X_HOME_URL = "https://x.com/home"
X_BOOKMARKS_URL = "https://x.com/i/bookmarks"

LI_LOGIN_URL = "https://www.linkedin.com/login"
LI_SAVED_URL = "https://www.linkedin.com/my-items/saved-posts/"


def _playwright_cookies_to_netscape(cookies: list[dict], domain_filter: str) -> str:
    """Convert Playwright cookie dicts to Netscape cookies.txt format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by cookie_refresher.py",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        if domain_filter not in domain:
            continue
        http_only = "TRUE" if c.get("httpOnly") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0)) if c.get("expires", -1) > 0 else 0
        path = c.get("path", "/")
        name = c.get("name", "")
        value = c.get("value", "")
        # domain field: prepend dot if not present for host-wide cookies
        if domain and not domain.startswith("."):
            domain = "." + domain
        lines.append(f"{domain}\t{http_only}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


async def _is_logged_in_x(context: BrowserContext) -> bool:
    """Check X.com auth by visiting bookmarks — redirects to login if not authed."""
    page = await context.new_page()
    try:
        await page.goto(X_BOOKMARKS_URL, wait_until="domcontentloaded", timeout=30000)
        await page.wait_for_timeout(3000)
        url = page.url
        return "login" not in url and "x.com/i/bookmarks" in url or "x.com/home" in url
    except Exception:
        return False
    finally:
        await page.close()


async def _is_logged_in_linkedin(context: BrowserContext) -> bool:
    """Check LinkedIn auth by visiting saved posts — redirects to login if not authed."""
    page = await context.new_page()
    try:
        await page.goto(LI_SAVED_URL, wait_until="domcontentloaded", timeout=30000)
        await page.wait_for_timeout(3000)
        url = page.url
        return "login" not in url and "authwall" not in url
    except Exception:
        return False
    finally:
        await page.close()


async def _wait_for_login(page, check_url_fragment: str, platform: str) -> None:
    """Wait until the browser navigates away from the login page."""
    print(f"\n[{platform}] Please log in in the browser window that just opened.")
    print(f"[{platform}] Waiting for you to complete the login...")

    deadline = time.time() + 300  # 5-minute timeout
    while time.time() < deadline:
        url = page.url
        if check_url_fragment in url and "login" not in url and "authwall" not in url:
            print(f"[{platform}] Login detected! Saving cookies...")
            return
        await asyncio.sleep(2)

    raise TimeoutError(f"[{platform}] Login not detected within 5 minutes.")


async def refresh_x_cookies(user_data_dir: Path) -> bool:
    """Open a visible browser to log in to X.com and save refreshed cookies."""
    output_file = user_data_dir / "x_cookies.txt"
    pw = await async_playwright().start()
    try:
        context = await pw.chromium.launch_persistent_context(
            user_data_dir=str(user_data_dir / "_refresh_x"),
            headless=False,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
        )
        page = await context.new_page()

        # Check if already logged in
        await page.goto(X_BOOKMARKS_URL, wait_until="domcontentloaded", timeout=30000)
        await page.wait_for_timeout(3000)
        if "login" not in page.url and "x.com" in page.url:
            print("[X] Already logged in.")
        else:
            await page.goto(X_LOGIN_URL, wait_until="domcontentloaded", timeout=30000)
            await _wait_for_login(page, "x.com", "X")

        # Export cookies
        cookies = await context.cookies(["https://x.com", "https://twitter.com"])
        netscape = _playwright_cookies_to_netscape(cookies, "x.com")
        # Also include twitter.com cookies (X uses both domains)
        netscape += _playwright_cookies_to_netscape(cookies, "twitter.com").split("\n", 3)[-1]

        output_file.write_text(netscape, encoding="utf-8")
        print(f"[X] Cookies saved to {output_file} ({len(cookies)} cookies)")
        await context.close()
    finally:
        await pw.stop()
    return True


async def refresh_linkedin_cookies(user_data_dir: Path) -> bool:
    """Open a visible browser to log in to LinkedIn and save refreshed cookies."""
    output_file = user_data_dir / "li_cookies.txt"
    pw = await async_playwright().start()
    try:
        context = await pw.chromium.launch_persistent_context(
            user_data_dir=str(user_data_dir / "_refresh_li"),
            headless=False,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
        )
        page = await context.new_page()

        await page.goto(LI_SAVED_URL, wait_until="domcontentloaded", timeout=30000)
        await page.wait_for_timeout(3000)

        if "login" not in page.url and "authwall" not in page.url:
            print("[LinkedIn] Already logged in.")
        else:
            await page.goto(LI_LOGIN_URL, wait_until="domcontentloaded", timeout=30000)
            await _wait_for_login(page, "linkedin.com", "LinkedIn")

        cookies = await context.cookies(["https://www.linkedin.com"])
        netscape = _playwright_cookies_to_netscape(cookies, "linkedin.com")
        output_file.write_text(netscape, encoding="utf-8")
        print(f"[LinkedIn] Cookies saved to {output_file} ({len(cookies)} cookies)")
        await context.close()
    finally:
        await pw.stop()
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Refresh X.com and/or LinkedIn cookies")
    parser.add_argument(
        "--platform",
        choices=["x", "linkedin", "both"],
        default="both",
        help="Which platform to refresh (default: both)",
    )
    parser.add_argument(
        "--user-data-dir",
        type=Path,
        default=USER_DATA_DIR,
        help=f"Cookie output directory (default: {USER_DATA_DIR})",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

    args.user_data_dir.mkdir(parents=True, exist_ok=True)

    if args.platform in ("x", "both"):
        asyncio.run(refresh_x_cookies(args.user_data_dir))

    if args.platform in ("linkedin", "both"):
        asyncio.run(refresh_linkedin_cookies(args.user_data_dir))

    print("\nDone! You can now run the pipeline: python main.py")


if __name__ == "__main__":
    main()
